server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      topic: EMJU_C02_CLIPS
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: emju-audit-dev
